"""Configuration for global serial-section semantic atlases."""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any

from histopia._validation import (
    finite_float,
    nonnegative_int,
    positive_float,
    positive_int,
)


@dataclass(slots=True)
class SemanticAtlasConfig:
    """Inputs and reproducibility controls for one semantic-atlas run."""

    registration_run: Path
    output_dir: Path
    model_cache_dir: Path | None = None
    analysis_mpp: float = 0.5
    patch_size_px: int = 224
    min_tissue_fraction: float = 0.5
    batch_size: int = 64
    patch_workers: int = 1
    vips_threads: int | None = None
    fit_threads: int = 4
    cluster_min: int = 5
    cluster_max: int = 15
    selected_clusters: int | None = None
    primary_clusters: int | None = None
    sensitivity_clusters: tuple[int, ...] = ()
    pca_components: int = 64
    balanced_patch_cap: int = 4096
    max_cross_section_distance_um: float = 112.0
    seed: int = 0
    device: str = "auto"

    def __post_init__(self) -> None:
        self.registration_run = Path(self.registration_run)
        self.output_dir = Path(self.output_dir)
        if self.model_cache_dir is not None:
            self.model_cache_dir = Path(self.model_cache_dir)
        self.analysis_mpp = positive_float("analysis_mpp", self.analysis_mpp)
        self.patch_size_px = positive_int("patch_size_px", self.patch_size_px)
        self.batch_size = positive_int("batch_size", self.batch_size)
        self.patch_workers = positive_int("patch_workers", self.patch_workers)
        if self.vips_threads is not None:
            self.vips_threads = positive_int("vips_threads", self.vips_threads)
        self.fit_threads = positive_int("fit_threads", self.fit_threads)
        self.min_tissue_fraction = finite_float(
            "min_tissue_fraction",
            self.min_tissue_fraction,
        )
        if not 0 <= self.min_tissue_fraction <= 1:
            raise ValueError("min_tissue_fraction must be between 0 and 1")
        self.cluster_min = positive_int("cluster_min", self.cluster_min)
        self.cluster_max = positive_int("cluster_max", self.cluster_max)
        self.selected_clusters = _optional_positive_int(
            "selected_clusters",
            self.selected_clusters,
        )
        self.primary_clusters = _optional_positive_int(
            "primary_clusters",
            self.primary_clusters,
        )
        self.sensitivity_clusters = tuple(
            positive_int("sensitivity_clusters", value)
            for value in self.sensitivity_clusters
        )
        self.pca_components = positive_int("pca_components", self.pca_components)
        self.balanced_patch_cap = positive_int(
            "balanced_patch_cap",
            self.balanced_patch_cap,
        )
        self.max_cross_section_distance_um = positive_float(
            "max_cross_section_distance_um",
            self.max_cross_section_distance_um,
        )
        self.seed = nonnegative_int("seed", self.seed)
        if self.seed > 2**32 - 1:
            raise ValueError("seed must not exceed 2**32 - 1")
        if not isinstance(self.device, str):
            raise TypeError("device must be a string")
        normalized_device = self.device.strip().lower()
        if (
            normalized_device
            not in {
                "auto",
                "cpu",
                "cuda",
                "mps",
            }
            and re.fullmatch(r"cuda:[0-9]+", normalized_device) is None
        ):
            raise ValueError("device must be auto, cpu, cuda, cuda:N, or mps")
        self.device = normalized_device
        requested = (
            tuple(
                value
                for value in (self.selected_clusters, self.primary_clusters)
                if value is not None
            )
            + self.sensitivity_clusters
        )
        if self.cluster_min <= 1 or self.cluster_max < self.cluster_min:
            raise ValueError("cluster range must contain values greater than one")
        if any(x <= 1 for x in requested):
            raise ValueError("cluster counts must be greater than one")
        if (
            self.selected_clusters is not None
            and self.selected_clusters not in self.cluster_counts
        ):
            raise ValueError("selected_clusters must be generated by cluster_counts")

    @property
    def cluster_counts(self) -> tuple[int, ...]:
        legacy = tuple(
            value
            for value in (self.primary_clusters, *self.sensitivity_clusters)
            if value is not None
        )
        if legacy:
            return tuple(dict.fromkeys(legacy))
        return tuple(range(self.cluster_min, self.cluster_max + 1))


def load_semantic_config(path: Path | str) -> SemanticAtlasConfig:
    """Load JSON or TOML configuration without importing heavy dependencies."""

    path = Path(path)
    if path.suffix.lower() == ".json":
        data: dict[str, Any] = json.loads(path.read_text())
    elif path.suffix.lower() in {".toml", ".tml"}:
        if sys.version_info >= (3, 11):
            import tomllib
        else:
            import tomli as tomllib
        data = tomllib.loads(path.read_text())
    else:
        raise ValueError("config must be JSON or TOML")
    data = dict(data)
    sensitivity = data.pop("sensitivity_clusters", ())
    return SemanticAtlasConfig(
        **data,
        sensitivity_clusters=tuple(sensitivity),
    )


def override_compute_config(
    config: SemanticAtlasConfig,
    *,
    device: str | None = None,
    batch_size: int | None = None,
    patch_workers: int | None = None,
    vips_threads: int | None = None,
    fit_threads: int | None = None,
) -> SemanticAtlasConfig:
    """Return a validated config with explicit command-line compute overrides."""

    overrides = {
        name: value
        for name, value in {
            "device": device,
            "batch_size": batch_size,
            "patch_workers": patch_workers,
            "vips_threads": vips_threads,
            "fit_threads": fit_threads,
        }.items()
        if value is not None
    }
    return replace(config, **overrides)


def _optional_positive_int(name: str, value: object | None) -> int | None:
    return None if value is None else positive_int(name, value)
