"""Configuration for global serial-section semantic atlases."""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(slots=True)
class SemanticAtlasConfig:
    """Inputs and reproducibility controls for one semantic-atlas run."""

    registration_run: Path
    output_dir: Path
    model_cache_dir: Path | None = None
    analysis_mpp: float = 0.5
    patch_size_px: int = 224
    min_tissue_fraction: float = 0.5
    batch_size: int = 64
    cluster_min: int = 5
    cluster_max: int = 15
    selected_clusters: int | None = None
    primary_clusters: int | None = None
    sensitivity_clusters: tuple[int, ...] = ()
    pca_components: int = 64
    balanced_patch_cap: int = 4096
    max_cross_section_distance_um: float = 112.0
    seed: int = 0
    device: str = "cuda"

    def __post_init__(self) -> None:
        self.registration_run = Path(self.registration_run)
        self.output_dir = Path(self.output_dir)
        if self.model_cache_dir is not None:
            self.model_cache_dir = Path(self.model_cache_dir)
        if self.analysis_mpp <= 0 or self.patch_size_px <= 0 or self.batch_size <= 0:
            raise ValueError(
                "analysis scale, patch size, and batch size must be positive"
            )
        if not 0 <= self.min_tissue_fraction <= 1:
            raise ValueError("min_tissue_fraction must be between 0 and 1")
        requested = (
            tuple(
                value
                for value in (self.selected_clusters, self.primary_clusters)
                if value is not None
            )
            + self.sensitivity_clusters
        )
        if self.cluster_min <= 1 or self.cluster_max < self.cluster_min:
            raise ValueError("cluster range must contain values greater than one")
        if any(x <= 1 for x in requested):
            raise ValueError("cluster counts must be greater than one")
        if (
            self.selected_clusters is not None
            and self.selected_clusters not in self.cluster_counts
        ):
            raise ValueError("selected_clusters must be generated by cluster_counts")

    @property
    def cluster_counts(self) -> tuple[int, ...]:
        legacy = tuple(
            value
            for value in (self.primary_clusters, *self.sensitivity_clusters)
            if value is not None
        )
        if legacy:
            return tuple(dict.fromkeys(legacy))
        return tuple(range(self.cluster_min, self.cluster_max + 1))


def load_semantic_config(path: Path | str) -> SemanticAtlasConfig:
    """Load JSON or TOML configuration without importing heavy dependencies."""

    path = Path(path)
    if path.suffix.lower() == ".json":
        data: dict[str, Any] = json.loads(path.read_text())
    elif path.suffix.lower() in {".toml", ".tml"}:
        if sys.version_info >= (3, 11):
            import tomllib
        else:
            import tomli as tomllib
        data = tomllib.loads(path.read_text())
    else:
        raise ValueError("config must be JSON or TOML")
    sensitivity = data.pop("sensitivity_clusters", ())
    return SemanticAtlasConfig(
        **data,
        sensitivity_clusters=tuple(int(value) for value in sensitivity),
    )
